services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=some-user
      - POSTGRES_PASSWORD=some-pass
      - POSTGRES_DB=some-db
  php:
    build:
      ./docker/php
    volumes:
      - .:/var/www:delegated
    links:
      - db
  nginx:
    image: nginx:1.27
    ports:
      - "8089:80"
    volumes:
      - .:/var/www:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
